name: Python Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - '.github/workflows/python-test.yml'
      - 'requirements*.txt'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.py'
      - '.github/workflows/python-test.yml'
      - 'requirements*.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pyscripts/requirements.txt

    - name: Run tests with pytest
      run: |
        pytest pyscripts/test/ --cov=pyscripts --cov-report=xml -v

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: haochengxia/vscode-pydata-viewer
